### ISSUE TITLE
Confused when trying to apply the tutorial to an existing Django project

### ISSUE THREAD

**Issue by andybak** [hitchtest/hitch#1]
It would be good to have a tutorial on how to use Hitch with an existing Django project. The current tutorial is fairly confusing for someone trying to use it as part of an existing project that already has tests.
1. The apt-get, npm and brew parts are irrelevant. Like most devs - I've already got a working local install of my app so I skipped these and went to the next bit.
2. sudo pip? pipsi? huh? I'll just 'pip install hitch' into my existing virtualenv and hope that works
3. mkdir tests?. hmmm. I don't want a tests directory in my project root so I'll substitute hitch_tests for now
4. "Inside the tests directory, run this command: hitch init" - OK. I'll try 'hitch init' from inside my 'hitch_tests' dir. Crikey. It's creating a virtualenv inside my virtualenv and installing stuff into it! Peculiar but let's ride with it for now.
5. "Hitch init will also create a file called hitchreqs.txt in your project directory" - no. Actually it created that inside the hitch_tests dir. Have I made a mistake or are the docs wrong?
6. Creating the engine file - it doesn't tell you what to save the file as - I'm guessing 'engine.py' for now.
7. Create stub.yml.
8. Run "hitch test tests/template.yml" - should that have been 'hitch test stub.yml"? After all - I'm still in the tests dir as I haven't been told to cd .. - I try every variant I can think of and all I get is "I didn't understand xxx.yml"

I hope the above is some use. I'm personally stuck and I'm off to try a couple of other test frameworks but I'll check back as lots of things about hitch look promising.

**Comment by crdoconnor** [comment]
The tutorial is about two weeks out of date. Sorry about that. I should have pointed you to this instead:

https://github.com/hitchtest/django-remindme-tests

This repo README highlights the most up to date way to install and use hitch, currently. I'll update the tutorial tomorrow.

As to your points:

#1 - Not all of the prerequisites are for running your application; some are for the framework.

#2 - pip install hitch just loads the bootstrap script. It sets up its own virtualenv for your tests to use, and your test can set up a virtualenv for your application too (that's what the example test does).

#3 - not a problem.

#5 - yes, it's supposed to create it in the test directory. See the django-remindme-tests project to see an example.

#6 - that will do, yes.

#7 - ignore that, it's out of date. Test filenames should have the extension .test.

If you're stuck, I recommend following the django-remindme-tests README. Follow that and see how it runs and then try adapting that to your project.

**Comment by andybak** [comment]
#1 - I suppose it would be useful to know which if hitch (separate from remindme) has any dependencies that aren't automatically handled by pip install. (apart from obvious things such as python, virtualenv, pip)

#2 - I think the subject of "it" in the second sentence is ambiguous. Is this a fair rephrasing?: "'pip install hitch' just installs the bootstrap script. When you later run this bootstrap script in your project it will set up its own virtualenv for your tests to use - and your test can set up a virtualenv for your application too (that's what the example test does)."

I'll have another try this week. I'll note down my steps and I might try and put together a small pull request for the docs if I have anything useful to add.

**Comment by crdoconnor** [comment]
#1 - it's just python 3, virtualenv and automake. This will be noted in the quickstart docs I'm writing.

#2 - yes, that's accurate.

I understand that the docs need some serious work. I'm creating a new set right now (quickstart) for people in your position - who want to create tests for an existing project.

It should be ready in one or two days, at which point I'd be very happy if you took another shot at this.

**Comment by andybak** [comment]
> python 3

Our project codebase is 2.7. Do you envisage using Hitch to test Python 2.7 code being an issue? I'm guessing that's fine as it's launching a separate process (unlike how Selenium works usually when run in Django's test suite).

**Comment by crdoconnor** [comment]
Nope, not a problem. The example test for instance, runs the same remindme test in v2.7 (passing) and then again in python 3.4 (where it demonstrates a failure).

It just means that anything you write in the engine.py has to be python 3.

**Comment by crdoconnor** [comment]
It's not yet complete, but I have shored up the docs and I have the basics of a generic quickstart guide available now:

https://hitchtest.readthedocs.org/en/latest/quickstart/index.html

I'll be adding to it over the weekend.

**Comment by crdoconnor** [comment]
The docs have been improved upon a lot since this issue was raised and are in a much more reasonable state now. I'm pretty sure of the issues raised here are now covered in one way or another.

Thanks for helping out. Please do raise any other issues if you see anything that's confusing.

**Comment by Eraldo** [comment]
The mention was not intended.. sorry.
