### ISSUE TITLE
Run tests in CI

### ISSUE THREAD

**Issue by thedrow** [hitchtest/hitch#16]
hitch needs a CI process that will run the tests and report any problems, lessening contribution friction and allowing more PRs to be easily submitted.

**Comment by crdoconnor** [comment]
I've got one it's just unwieldly and not really something I can really run on travis or equivalent. I currently run the framework's regression tests on multiple environments (Mac OS mavericks + yosemite, Ubuntu, Debian, Fedora, Arch) and I'm expanding it to cover more. I'm also dogfooding the development version, of course.

If you submit a pull request and it looks decent I'll accept it. If it causes regression bugs that I didn't spot in the PR (as a previous PR did - there was a python 2/3 incompatibility that slipped my notice) I'm ok with that. I always run the full suite before pushing to pypi anyway.
