### ISSUE TITLE
clicking invisible elements -- try catch block ignored -- ElementNotVisibleException

### ISSUE THREAD

**Issue by Eraldo** [hitchtest/hitch#19]
I am trying to get an element (button styled link) that is not initially visible because it comes into vision via a javascript animation.

The default engine click method looked like this:

``` python
    def click(self, on):
        """Click on HTML id."""
        self.driver.find_element_by_id(on).click()
```

Using these test lines:

```
- Load website
- Click: join-explorer
```

I get this error:
`selenium.common.exceptions.ElementNotVisibleException`

I tried to alter the engine method like this:

``` python
    def click(self, on):
        """Click on HTML id."""
        try:
            self.driver.find_element_by_id(on).click()
        except ElementNotVisibleException:
            self.find_element_by_xpath("//a[@id = '{}']".format(on)).click()
```

Problem 1: I do not know how to import `ElementNotVisibleException` since it is part of `selenium` not `hitchselenium`.
Problem 2: Somehow the try except block is ignored during the test. That is.. even this triggers the error:

``` python
    def click(self, on):
        """Click on HTML id."""
        try:
            self.driver.find_element_by_id(on).click()
        except:  # should not be used
            pass
```

Any ideas on how to approach this?

Greetings from Berlin..
Eraldo

**Comment by crdoconnor** [comment]
Hi Eraldo!

> I am trying to get an element (button styled link) that is not initially visible because it comes into vision via a javascript animation.

For this type of thing you need to have a step before the click to wait for it to appear, which isn't so easy to do with selenium.

This is actually one of the tasks that made me create a selenium step library. 

You can activate it by putting the following in your set_up::

```
    self.driver = self.services['Firefox'].driver

    self.webapp = hitchselenium.SeleniumStepLibrary(
        selenium_webdriver=self.driver,
        wait_for_timeout=5,
    )

    self.click = self.webapp.click
    self.wait_to_appear = self.webapp.wait_to_appear
    self.wait_to_contain = self.webapp.wait_to_contain
    self.wait_for_any_to_contain = self.webapp.wait_for_any_to_contain
    self.click_and_dont_wait_for_page_load = self.webapp.click_and_dont_wait_for_page_load
```

These docs should tell you how to use these steps:

https://hitchtest.readthedocs.org/en/latest/howto/web_applications.html

In your case it looks like you'd need::

```
- Load website
- Wait to appear: join-explorer
- Click: join-explorer
```

**Comment by crdoconnor** [comment]
Let me know if that works for you.

**Comment by Eraldo** [comment]
Meow @crdoconnor..

Thank you for the quick reply - I appreciate that a lot. :D
1. I commented out that this line:

``` python
self.wait_to_contain = self.webapp.wait_to_contain
```

Since it gave me this error (trace):

``` python
    111 :         self.click = self.webapp.click
--> 112 :         self.wait_to_appear = self.webapp.wait_to_appear
    113 :         self.wait_to_contain = self.webapp.wait_to_contain
    114 :         self.wait_for_any_to_contain = self.webapp.wait_for_any_to_contain

builtins.AttributeError

'SeleniumStepLibrary' object has no attribute 'wait_to_appear'
```

Hitch version: `hitch==0.5.6`

Any ideas on that? What am I missing?

**Comment by Eraldo** [comment]
I also want to mention that the animation is triggered by scrolling to that part of the page (landing page).
So mere waiting might not solve the issue, or does it just need to wait for javascript in general?

I am only using that on one single page (landing page).. so a workaround would also be okay I guess. ;)

**Comment by crdoconnor** [comment]
That's weird. I think you may have an older version of hitchselenium installed if wait_to_appear is not part of it. Check your hitchreqs.txt. The latest is hitchselenium==0.4.8.

You may want to upgrade your hitch environment: https://hitchtest.readthedocs.org/en/latest/howto/upgrade_hitch.html

(let me know if that breaks something I'll tell you how to fix it).

> I also want to mention that the animation is triggered by scrolling to that part of the page (landing page). So mere waiting might not solve the issue

Gotcha. Ok, I guess you'll need to scroll it into view too. I'm not sure how to do that exactly, but I'll figure it out and add another step to the library.

I guess the code will need to be something like this: https://stackoverflow.com/questions/3401343/scroll-element-into-view-with-selenium

**Comment by Eraldo** [comment]
Oh,.. yes I was at `hitchselenium==0.4.5`
Yes, it did find it now. .oO( how embarrassing )

This worked great:

``` python
    def scroll_to(self, id):
        self.driver.execute_script('$("#{}").get(0).scrollIntoView();'.format(id))
```

Thank you for the hint! :D

**Comment by crdoconnor** [comment]
Awesome. I'll add that to the step library.
