### ISSUE TITLE
Running Test Stub; Error About Missing Requirements.txt

### ISSUE THREAD

**Issue by Stephen-Williams** [hitchtest/hitch#24]
I'm trying to install hitch by following the instructions here:
https://hitchtest.readthedocs.org/en/latest/quickstart/index.html

I've gotten to the point of running the stub test:
$ hitch test stub.test --settings tdd.settings

And it keeps failing with the following error.  It seems like it's trying to install/update pip and not finding a file it expects.  I followed all the direction on the page prior to this, so I don't know if this is because I should have installed something, or if hitch was supposed to auto-install somethign and didn't.  Any help would be appreciated!

> RUNNING TEST Stub
> Could not open requirements file: [Errno 2] No such file or directory: '/home/vagrant/requirements.txt'
> Python 3.4.3+ (default, Oct 14 2015, 16:03:50)
> Type "copyright", "credits" or "license" for more information.
> 
> IPython 4.0.2 -- An enhanced Interactive Python.
> ?         -> Introduction and overview of IPython's features.
> %quickref -> Quick reference.
> help      -> Python's own help system.
> object?   -> Details about 'object', use 'object??' for extra details.
> 
> Exception occurred in "Stub" setup
>     /home/vagrant/test/stub.test --tags feature-name
> 
> [0]: function 'set_up'   ( self.stacktrace[0].ipython() )
>   /home/vagrant/test/engine.py
> 
> ```
> 27 :         check_call([
> 28 :             python_package.pip, "install", "-r",
> ```
> 
> --> 29 :             path.join(PROJECT_DIRECTORY, "requirements.txt")
>     30 :         ])
>     31 :
> 
> [1]: function 'check_call'   ( self.stacktrace[1].ipython() )
>   /usr/lib/python3.4/subprocess.py
> 
> ```
> 559 :         if cmd is None:
> 560 :             cmd = popenargs[0]
> ```
> 
> --> 561 :         raise CalledProcessError(retcode, cmd)
>     562 :     return 0
>     563 :
> 
> subprocess.CalledProcessError
> 
> Command '['/home/vagrant/test/.hitch/py3.4.3/bin/pip', 'install', '-r', '/home/vagrant/requirements.txt']' returned non-zero exit status 1
> 
> FAILED IN 56.4 seconds

**Comment by crdoconnor** [comment]
Hi Stephen!

It's expecting a requirements.txt file containing a list of the python modules which your application requires to run.

By default it looks in the directory _above_ the directory that you put the tests in (it assumes that that is your project directory).

**Comment by crdoconnor** [comment]
Does that make sense?

**Comment by Stephen-Williams** [comment]
Yes, it does make sense, thank you.
However, my project actually has a few "requirements" files for different environments, for example:
requirements/dev.txt
requirements/prod.txt

Is there a way to tell hitch which file it should be using?
or, failing that, is there a way to just tell it "nothing is required"?  Could I put a blank requirements.txt in the parent directory?  Just to get the stub test through its thing.

**Comment by crdoconnor** [comment]
Well, you probably need to install something in a virtualenv if you're testing python/django/celery code (or are you testing something else?).

You can of course change the line in engine.py to whatever you want -- e.g. requirements/dev.txt instead of requirements.txt. You could also run two pip installs for two separate files just by copying and pasting that line:

```
    check_call([
        python_package.pip, "install", "-r",
        path.join(PROJECT_DIRECTORY, "requirements.txt")
    ])

    check_call([
        python_package.pip, "install", "-r",
        path.join(PROJECT_DIRECTORY, "requirements/dev.txt")
    ])
```

You can also comment this line out if you don't want it.

**Comment by Stephen-Williams** [comment]
Thanks for the assistance, that got things moving again!
