### ISSUE TITLE
Selenium - test that something does NOT appear

### ISSUE THREAD

**Issue by geokala** [hitchtest/hitch#26]
Hi,
I might have just missed it in the docs, but I'm trying to create a test that something is not present on the page under certain conditions- basically:
- Click: disable-registration
- Click: logout
- <something that means it couldn't find the target object>: registration

Is there currently a simple way to do this, or to say "Click but reverse failure and success conditions"?

**Comment by crdoconnor** [comment]
Nope, not in the docs. You need to write a step that waits for the element to appear for a number of seconds, raises an exception if it does and doesn't raise an exception if it doesn't.

Something like this should work (note not tested!):

```
def verify_that_element_does_not_appear(self, item):
    """Only raise exception if element does appear."""
    from selenium.common.exceptions import TimeoutException
    try:
        self.wait_to_appear(item)
        raise RuntimeError("Item {} appeared".format(item))
    except TimeoutException:
        pass
```

Note that this kind of step can slow down your test because the engine has to wait for a set period of time before going "yup, this element isn't going to appear".

**Comment by geokala** [comment]
Just as a quick update, the following code has been working for me (exactly as you wrote, except the name, I think):

```
    def should_not_appear(self, item):
        """Only raise exception if element does appear."""
        from selenium.common.exceptions import TimeoutException
        try:
            self.wait_to_appear(item)
            raise RuntimeError("Item {} appeared".format(item))
        except TimeoutException:
            pass
```

If this is something you're likely to want to include, I can look at raising a PR perhaps. Otherwise, I'm happy for this to be closed.

**Comment by crdoconnor** [comment]
Will add it later tonight. Thanks @geokala !

**Comment by crdoconnor** [comment]
Or if you want to raise a PR I'll be happy to include it on hitchselenium.
