### ISSUE TITLE
Error on El Capitan

### ISSUE THREAD

**Issue by mimischi** [hitchtest/hitch#28]
Hi,

I'm trying to run hitchtest on OS X El Capitan. Your docs say that this version has not been tested yet and it doesn't seem to work.

I've got two different bug reports. Running your example project (https://github.com/hitchtest/django-remindme-tests) and following the installation, I get the following error:
[django-remindme-error.txt](https://github.com/hitchtest/hitch/files/222258/django-remindme-error.txt)

Running hitch on a newly created cookiecutter-django project, I get the following:
[cookiecutter-hitch-error.txt](https://github.com/hitchtest/hitch/files/222261/cookiecutter-hitch-error.txt)

It seems like hitch tries to access the python 2.7.11 interpreter or even replace out-dated system-wide python packages? Not quite sure if I'm doing anything wrong. Just updated brew, upgraded all things and made sure python3 and python2 are up-to-date.

**Comment by crdoconnor** [comment]
I actually did try it on El Capitan before and it was working fine (as of three weeks ago). I'm still not able to regularly test it on El Capitan because there's no VM for it yet and I don't have a Mac. Unfortunately at some point something will be changed on that system which will break something though :(

This looks like something different though.

Hitch doesn't try to change system-wide python packages (that would be rude). It tries to install its own isolated version of python using pyenv which it then uses to create virtualenvs and it tries to ensure prerequisite packages are installed using the package manager (stuff like libjpeg).

However, weirdly it looks like your system might be using virtualenv as if it were using --system-site-packages _by default_, which is why it's trying to use an outdated pyyaml in example 2 and example 1 is attempting to upgrade a _system_ (as opposed to virtualenv) version of setuptools.

**Comment by crdoconnor** [comment]
Can you try creating a virtualenv yourself and seeing if you can upgrade setuptools in the virtualenv?

**Comment by mimischi** [comment]
Just created a new virtualenv and activated it. Not sure if it changes anything?

[error2.txt](https://github.com/hitchtest/hitch/files/222277/error2.txt)

I think there is some change in El Capitan that does not allow changing system packages, which was possible before (not sure on that though..)? Anything else I should test?

**Comment by crdoconnor** [comment]
Does:

```
/Users/mischi/Documents/Code/flatmate_dj/tests/.hitch/virtualenv/bin/pip freeze
```

Show packages which are not listed in hitchreqs.txt?

**Comment by crdoconnor** [comment]
You could also try this (this mimics how hitch sets up its own virtualenv)::

```
virtualenv tempvirtualenv --python=python3

./tempvirtualenv/bin/pip install --upgrade pip
./tempvirtualenv/bin/pip install --upgrade setuptools
./tempvirtualenv/bin/pip install PyYAML
./tempvirtualenv/bin/python

>>> import yaml
```

I'm wondering if this isn't caused by system python2 virtualenv attempting to set up a python3 virtualenv on a mac (i.e. a bug in the latest version of virtualenv).

These lines in particular are making me suspicious::

```
  File "/Users/mischi/Documents/Code/flatmate_dj/tests/.hitch/virtualenv/lib/python3.5/site-packages/hitchtest/step.py", line 3, in <module>
    import yaml
  File "/Library/Python/2.7/site-packages/yaml/__init__.py", line 2, in <module>
    from error import *
ImportError: No module named 'error'
```

That's a python3 virtualenv code calling python 2 system code which shouldn't happen, ever.

**Comment by mimischi** [comment]
There is no .hitch folder after calling the init command. That's kinda weird. Just tried other suggestion:

```
Michaels-MacBook-Pro:Documents mischi$ mkdir test
Michaels-MacBook-Pro:Documents mischi$ cd test
Michaels-MacBook-Pro:test mischi$ virtualenv tempvirtualenv --python=python3
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5'
New python executable in /Users/mischi/Documents/test/tempvirtualenv/bin/python3.5
Also creating executable in /Users/mischi/Documents/test/tempvirtualenv/bin/python
Installing setuptools, pip, wheel...done.
Michaels-MacBook-Pro:test mischi$ ./tempvirtualenv/bin/pip install --upgrade pip
Requirement already up-to-date: pip in /Library/Python/2.7/site-packages
Michaels-MacBook-Pro:test mischi$ ./tempvirtualenv/bin/pip install --upgrade setuptools
Requirement already up-to-date: setuptools in ./tempvirtualenv/lib/python3.5/site-packages
Michaels-MacBook-Pro:test mischi$ ./tempvirtualenv/bin/pip install PyYAML
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /Library/Python/2.7/site-packages
Michaels-MacBook-Pro:test mischi$ ./tempvirtualenv/bin/python
Python 3.5.1 (default, Apr  5 2016, 21:27:05) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/yaml/__init__.py", line 2, in <module>
    from error import *
ImportError: No module named 'error'
>>> 
```

**Comment by crdoconnor** [comment]
Ok yea it looks like something is up with your virtualenv.

I've created an issue on the virtualenv bug tracker to see if they can figure out why this might be happening:

https://github.com/pypa/virtualenv/issues/890

**Comment by mimischi** [comment]
Just went ahead and tried to fix the issue. Looks like my python installation was screwed up. I've spent a few hours playing around with the python installed from python.org, Anaconda and python from both MacPorts and Homebrew. What I ended up doing was: delete everything.

For MacPorts (use only if you've got nothing installed using MacPorts! **This will delete every port!**):
`sudo port -fp uninstalled installed`

For Anaconda:
`rm -rf ~/.anaconda*`

Furthermore I followed this Stackoverflow question: http://stackoverflow.com/a/3819829/4791226

In the end I re-installed python and python3 using Homebrew:
`brew update && brew install python python3`

After updating pip and pip3 (which were both working now!), I noticed that virtualenv was still installed from the previous testing:

```
Michaels-MBP:ENV mischi$ pip install virtualenv
Requirement already satisfied (use --upgrade to upgrade): virtualenv in /Users/mischi/Library/Python/2.7/lib/python/site-packages
Michaels-MBP:ENV mischi$ pip uninstall virtualenv
Uninstalling virtualenv-15.0.2:
  /Users/mischi/Library/Python/2.7/bin/virtualenv
  /Users/mischi/Library/Python/2.7/lib/python/site-packages/virtualenv-15.0.2.dist-info/DESCRIPTION.rst
  /Users/mischi/Library/Python/2.7/lib/python/site-packages/virtualenv-15.0.2.dist-info/INSTALLER
  /Users/mischi/Library/Python/2.7/lib/python/site-packages/virtualenv-15.0.2.dist-info/METADATA
  /Users/mischi/Library/Python/2.7/lib/python/site-packages/virtualenv-15.0.2.dist-info/RECORD
  /Users/mischi/Library/Python/2.7/lib/python/site-packages/virtualenv-15.0.2.dist-info/WHEEL
  /Users/mischi/Library/Python/2.7/lib/python/site-packages/virtualenv-15.0.2.dist-info/entry_points.txt
  /Users/mischi/Library/Python/2.7/lib/python/site-packages/virtualenv-15.0.2.dist-info/metadata.json
  /Users/mischi/Library/Python/2.7/lib/python/site-packages/virtualenv-15.0.2.dist-info/top_level.txt
  /Users/mischi/Library/Python/2.7/lib/python/site-packages/virtualenv.py
  /Users/mischi/Library/Python/2.7/lib/python/site-packages/virtualenv.pyc
  /Users/mischi/Library/Python/2.7/lib/python/site-packages/virtualenv_support/__init__.py
  /Users/mischi/Library/Python/2.7/lib/python/site-packages/virtualenv_support/__init__.pyc
  /Users/mischi/Library/Python/2.7/lib/python/site-packages/virtualenv_support/argparse-1.4.0-py2.py3-none-any.whl
  /Users/mischi/Library/Python/2.7/lib/python/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl
  /Users/mischi/Library/Python/2.7/lib/python/site-packages/virtualenv_support/setuptools-21.2.1-py2.py3-none-any.whl
  /Users/mischi/Library/Python/2.7/lib/python/site-packages/virtualenv_support/wheel-0.29.0-py2.py3-none-any.whl
Proceed (y/n)? y
  Successfully uninstalled virtualenv-15.0.2
Michaels-MBP:ENV mischi$ pip install virtualenv --upgrade
Requirement already up-to-date: virtualenv in /usr/local/lib/python2.7/site-packages
```

I was just able to do `hitch init` on OS X El Capitan 10.11.6. So this issue is resolved!

**Comment by crdoconnor** [comment]
Thanks @mimischi!

What precisely happened to make this occur? Was it conflicting versions of python being installed side by side (from ports/python.org/brew)?

I'd like to write a check at the beginning of installation to ensure that this type of issue can be detected so a coherent error message can be given.

**Comment by mimischi** [comment]
I was not even able to run `python3` in the terminal. It gave the same error as trying to run hitch (which does make sense..): `ImportError: This package should not be accessible on Python 3`

So I can't really tell you what was actually wrong. Probably something with my $PATH/$PYTHONPATH was off and/or I've had several python installations pointing in different directions.
