### ISSUE TITLE
Error starting firefox for selenium on Ubuntu 14.04

### ISSUE THREAD

**Issue by geokala** [hitchtest/hitch#29]
Not sure if this is due to an updated version of firefox, or even some other peculiarity of my system, but I now seem to be experiencing the following error trying to run any tests with Selenium:

```
    194 :             if interactive:
    195 :                 self.start_interactive_mode()
--> 196 :             raise what_happened
    197 :         else:
    198 :             if interactive:



hitchserve.hitch_exception.ServiceSuddenStopException

Service 'Firefox' stopped suddenly.

FAILED IN 33.7 seconds
```

Is this a known (recent) issue?

**Comment by geokala** [comment]
As a side note, if I run it with the tdd.settings (so firefox shows up) then I can see that firefox actually starts, so I'm not sure where the error lies here.

**Comment by crdoconnor** [comment]
I've had something similar happen in the past with old versions of selenium trying to use the latest version of firefox, but I thought that that'd stopped happening.

If that is the problem, running "hitch install selenium" might fix the problem.

Which version of firefox are you using? Also, did you just update to xenial? :)

**Comment by crdoconnor** [comment]
Also, it might give a better error above in the logs marked [Firefox].

**Comment by geokala** [comment]
Good call on updating selenium.

I updated all packages on the system as well, and then ran (as you advised):
hitch install selenium

All working now, so this ticket can be killed, unless you want to keep it.

As for version, still on Trusty. Trying to keep as little systemd on here as I can get away with before I invest time to look at my options.

**Comment by crdoconnor** [comment]
Great! Thanks for getting back to me.
