### ISSUE TITLE
Error running hitch install to upgrade hitchselenium

### ISSUE THREAD

**Issue by geokala** [hitchtest/hitch#30]
I just saw the following error:
  File "/home/talkur/programming/turkey/tests/.hitch/virtualenv/lib/python3.4/site-packages/hitchserve/hitch_service.py", line 6, in <module>
    import commandlib
ImportError: No module named 'commandlib'

This was after running: hitch install hitchselenium==0.5.2

The hitch virtualenv currently has (from pip list AFTER the install):
click (6.2)
colorama (0.3.7)
decorator (4.0.6)
docopt (0.6.2)
faketime (0.9.6.3)
hitchpostgres (0.7.0)
hitchpython (0.5.2)
hitchquickstart (0.1.4)
hitchselenium (0.5.2)
hitchserve (0.4.9)
hitchsmtp (0.2.1)
hitchsystem (0.1.2)
hitchtest (0.9.6)
humanize (0.5.1)
ipython (4.0.3)
ipython-genutils (0.1.0)
Jinja2 (2.8)
MarkupSafe (0.23)
path.py (8.1.2)
patool (1.12)
pexpect (4.0.1)
pickleshare (0.6)
pip (8.1.0)
psutil (4.1.0)
ptyprocess (0.5)
pykwalify (1.5.0)
python-build (0.2.12)
python-dateutil (2.4.2)
pyuv (1.2.0)
PyYAML (3.11)
requests (2.9.1)
selenium (2.53.2)
setuptools (20.2.2)
simplegeneric (0.8.1)
six (1.10.0)
tblib (1.3.0)
traitlets (4.1.0)
unixpackage (0.4.0)

**Comment by crdoconnor** [comment]
Oops. Try running:

```
 hitch install commandlib
```

**Comment by crdoconnor** [comment]
Alternatively, just run:

```
hitch upgrade
```

Which will upgrade everything.

**Comment by geokala** [comment]
Yeah, that's what I'm just doing, as it appears that the hitch install left the environment in a broken state (can't run hitch test any more).

Just figured it was worth reporting in case there's anything reasonable that can be done to stop newly introduced sub-dependencies (of the hitch installed package) from causing this in future.

Will update this once the upgrade finishes to confirm it works.

**Comment by geokala** [comment]
After hitch upgrade:
pkg_resources.DistributionNotFound: The 'python-dateutil==2.4.2' distribution was not found and is required by pykwalify

*- when trying to hitch test

**Comment by crdoconnor** [comment]
Oh crap. That's caused by https://github.com/Grokzen/pykwalify/issues/55

If you hitch install python-dateutil==2.4.2 it should go away.

**Comment by geokala** [comment]
Ah- I .hitch/virtualenv/bin/pip installed that version, and indeed the test is running now!

**Comment by geokala** [comment]
Can close this unless there's any part of it that you think is worth patching (that is to say: I'm happy for you to close it, your choice!).

**Comment by crdoconnor** [comment]
I'm thinking of forking that project and unfixing the versions to prevent that from happening.

I've added commandlib as an explicit dependency on hitchserve now to prevent the previous error from happening.

**Comment by crdoconnor** [comment]
Yep, I'll raise the appropriate issues and link them here. Thanks once again @geokala !
