### ISSUE TITLE
No such file or directory on hitch clean (low priority)

### ISSUE THREAD

**Issue by phoebebright** [hitchtest/hitch#9]
If hitch init fails and left with a .hitch directory but no virtual env, then hitch clean will fail

hitcher@jenkins:/home/django/django-remindme/django-remindme-tests$ hitch clean
Traceback (most recent call last):
  File "/usr/local/bin/hitch", line 11, in <module>
    sys.exit(commandline.run())
  File "/usr/local/lib/python2.7/dist-packages/hitch/commandline.py", line 207, in run
    path.join(hitchdir.get_hitch_directory(), "virtualenv", "bin")
OSError: [Errno 2] No such file or directory: '/home/django/django-remindme/django-remindme-tests/.hitch/virtualenv/bin'

Solution is to manually delete .hitch

**Comment by crdoconnor** [comment]
Thanks for reporting. Will fix.

**Comment by crdoconnor** [comment]
Error message made more sensible in https://github.com/hitchtest/hitch/commit/b59bf64d38ea8a44e91f01c73e7d390cdb041cba

Fix available in v0.5.1
